name: CI/CD Workflow
on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the build and deploy on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Set the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      #   - name: Build
      #     run: npm run build # Replace with your build command

